### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Tomoaki-git** [Tomoaki-git/furima-34423#9]
# URL
https://furima-34423.herokuapp.com/

# Basic認証
ID :admin
password:2222

# 出品者用アカウント
ニックネーム：テスト1
メールアドレス：test1@gmail.com
パスワード：test1111

# 購入者用アカウント
ニックネーム：テスト2
メールアドレス：test2@gmail.com
パスワード：test2222

＊＊＊＊＊＊＊＊＊＊

動作確認の程、よろしくお願い致します！

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **パスワードは6文字が入力されていれば、登録可能としましょう**
現状7文字以上入力しないとユーザー登録ができません

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Tomoaki-git** [comment]
@mo1015 さん
失礼致しました！
修正しましたので、ご確認お願い致します！

**Comment by kinnkann** [comment]
ご提出ありがとうございます！
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/57080384/109440717-8a4d8d80-7a76-11eb-88c0-09749c3ed68a.png)
**

**Comment by Tomoaki-git** [comment]
@kinnkann さん
LGTMありがとうございました！！
